=begin
#Sajari API

#Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.

The version of the OpenAPI document: v4
Contact: support@sajari.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SajariAPIClient::PipelinesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PipelinesApi' do
  before do
    # run before each test
    @api_instance = SajariAPIClient::PipelinesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PipelinesApi' do
    it 'should create an instance of PipelinesApi' do
      expect(@api_instance).to be_instance_of(SajariAPIClient::PipelinesApi)
    end
  end

  # unit tests for create_pipeline
  # Create pipeline
  # Create a new pipeline.  Pipelines are immutable once created. If you want to change a pipeline e.g. to add or change some steps, you need to create a new version of that pipeline.  To start using a new pipeline you need to update your record ingestion calls and/or your query calls to specify the new pipeline.  To create the pipeline from YAML, set the request&#39;s &#x60;Content-Type&#x60; header to &#x60;application/yaml&#x60; and submit the pipeline&#39;s YAML in the request body.
  # @param collection_id The collection to create the pipeline in, e.g. &#x60;my-collection&#x60;.
  # @param pipeline The pipeline to create.
  # @param [Hash] opts the optional parameters
  # @return [Pipeline]
  describe 'create_pipeline test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for generate_pipelines
  # Generate pipelines
  # Generate basic record, query and autocomplete pipeline templates. Use these templates as a starting point for your collection&#39;s pipelines.  This call returns a set of pipelines that you can pass directly to the create pipeline call.  The generated templates can be returned in JSON, the default, or YAML. To return the generated pipelines in YAML, set the request&#39;s &#x60;Accept&#x60; header to &#x60;application/yaml&#x60;. The three pipelines in the YAML response are separated by three dashes (&#x60;---&#x60;).
  # @param collection_id The collection, e.g. &#x60;my-collection&#x60;.
  # @param generate_pipelines_request 
  # @param [Hash] opts the optional parameters
  # @return [GeneratePipelinesResponse]
  describe 'generate_pipelines test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_default_pipeline
  # Get default pipeline
  # Get the default pipeline for a collection.  Every collection has a default record pipeline and a default query pipeline.  When a pipeline is required to complete an operation, it can be omitted from the request if a default pipeline has been set. When adding a record to a collection, the default record pipeline is used if none is provided. When querying a collection, the default query pipeline is used if none is provided.
  # @param collection_id The collection to get the default query pipeline of, e.g. &#x60;my-collection&#x60;.
  # @param type The type of the pipeline to get.   - TYPE_UNSPECIFIED: Pipeline type not specified.  - RECORD: Record pipeline.  - QUERY: Query pipeline.
  # @param [Hash] opts the optional parameters
  # @return [GetDefaultPipelineResponse]
  describe 'get_default_pipeline test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_default_version
  # Get default pipeline version
  # Get the default version for a given pipeline.  The default version of a pipeline is used when a pipeline is referred to without specifying a version.  This allows you to change the pipeline version used for requests without having to change your code.  To retrieve the pipeline in YAML, set the request&#39;s &#x60;Accept&#x60; header to &#x60;application/yaml&#x60;.
  # @param collection_id The collection that owns the pipeline to get the default version of, e.g. &#x60;my-collection&#x60;.
  # @param type The type of the pipeline to get the default version of.
  # @param name The name of the pipeline to get the default version of, e.g. &#x60;my-pipeline&#x60;.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :view The amount of information to include in the retrieved pipeline.   - VIEW_UNSPECIFIED: The default / unset value. The API defaults to the &#x60;BASIC&#x60; view.  - BASIC: Include basic information including type, name, version and description but not the full step configuration. This is the default value (for both [ListPipelines](/api#operation/ListPipelines) and [GetPipeline](/api#operation/GetPipeline)).  - FULL: Include the information from &#x60;BASIC&#x60;, plus full step configuration.
  # @return [Pipeline]
  describe 'get_default_version test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_pipeline
  # Get pipeline
  # Retrieve the details of a pipeline. Supply the type, name and version.  To retrieve the pipeline in YAML, set the request&#39;s &#x60;Accept&#x60; header to &#x60;application/yaml&#x60;.
  # @param collection_id The collection that owns the pipeline, e.g. &#x60;my-collection&#x60;.
  # @param type The type of the pipeline to retrieve.
  # @param name The name of the pipeline to retrieve, e.g. &#x60;my-pipeline&#x60;.
  # @param version The version of the pipeline to retrieve, e.g. &#x60;42&#x60;.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :view The amount of information to include in the retrieved pipeline.   - VIEW_UNSPECIFIED: The default / unset value. The API defaults to the &#x60;BASIC&#x60; view.  - BASIC: Include basic information including type, name, version and description but not the full step configuration. This is the default value (for both [ListPipelines](/api#operation/ListPipelines) and [GetPipeline](/api#operation/GetPipeline)).  - FULL: Include the information from &#x60;BASIC&#x60;, plus full step configuration.
  # @return [Pipeline]
  describe 'get_pipeline test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_pipelines
  # List pipelines
  # Retrieve a list of pipelines.
  # @param collection_id The collection that owns this set of pipelines, e.g. &#x60;my-collection&#x60;.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_size The maximum number of pipelines to return. The service may return fewer than this value.  If unspecified, at most 50 pipelines are returned.  The maximum value is 1000; values above 1000 are coerced to 1000.
  # @option opts [String] :page_token A page token, received from a previous [ListPipelines](/api#operation/ListPipelines) call.  Provide this to retrieve the subsequent page.  When paginating, all other parameters provided to [ListPipelines](/api#operation/ListPipelines) must match the call that provided the page token.
  # @option opts [String] :view The amount of information to include in each retrieved pipeline.   - VIEW_UNSPECIFIED: The default / unset value. The API defaults to the &#x60;BASIC&#x60; view.  - BASIC: Include basic information including type, name, version and description but not the full step configuration. This is the default value (for both [ListPipelines](/api#operation/ListPipelines) and [GetPipeline](/api#operation/GetPipeline)).  - FULL: Include the information from &#x60;BASIC&#x60;, plus full step configuration.
  # @return [ListPipelinesResponse]
  describe 'list_pipelines test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_default_pipeline
  # Set default pipeline
  # Set the default pipeline for a collection.  Every collection has a default record pipeline and a default query pipeline.  When a pipeline is required to complete an operation, it can be omitted from the request if a default pipeline has been set. When adding a record to a collection, the default record pipeline is used if none is provided. When querying a collection, the default query pipeline is used if none is provided.  Once a default pipeline has been set it cannot be cleared, only set to another pipeline.
  # @param collection_id The collection to set the default query pipeline of, e.g. &#x60;my-collection&#x60;.
  # @param set_default_pipeline_request 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'set_default_pipeline test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_default_version
  # Set default pipeline version
  # Set the default version for a given pipeline.  The default version of a pipeline is used when a pipeline is referred to without specifying a version.  This allows you to change the pipeline version used for requests without having to change your code.
  # @param collection_id The collection that owns the pipeline to set the default version of, e.g. &#x60;my-collection&#x60;.
  # @param type The type of the pipeline to set the default version of.
  # @param name The name of the pipeline to set the default version of, e.g. &#x60;my-pipeline&#x60;.
  # @param set_default_version_request 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'set_default_version test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
