=begin
#Sajari API

#Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.

The version of the OpenAPI document: v4
Contact: support@sajari.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SajariAPIClient::SchemaApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SchemaApi' do
  before do
    # run before each test
    @api_instance = SajariAPIClient::SchemaApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SchemaApi' do
    it 'should create an instance of SchemaApi' do
      expect(@api_instance).to be_instance_of(SajariAPIClient::SchemaApi)
    end
  end

  # unit tests for batch_create_schema_fields
  # Batch create schema fields
  # The batch version of the [CreateSchemaField](/api#operation/CreateSchemaField) call.
  # @param collection_id The collection to create the schema fields in, e.g. &#x60;my-collection&#x60;.
  # @param batch_create_schema_fields_request 
  # @param [Hash] opts the optional parameters
  # @return [BatchCreateSchemaFieldsResponse]
  describe 'batch_create_schema_fields test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_schema_field
  # Create schema field
  # Create a new field in your collection&#39;s schema.
  # @param collection_id The collection to create a schema field in, e.g. &#x60;my-collection&#x60;.
  # @param schema_field The schema field to create.
  # @param [Hash] opts the optional parameters
  # @return [SchemaField]
  describe 'create_schema_field test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_schema_fields
  # List schema fields
  # Retrieve a list of schema fields in the collection.
  # @param collection_id The collection that owns this set of schema fields, e.g. &#x60;my-collection&#x60;.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_size The maximum number of schema fields to return. The service may return fewer than this value.  If unspecified, at most 50 schema fields are returned.  The maximum value is 1000; values above 1000 are coerced to 1000.
  # @option opts [String] :page_token A page token, received from a previous [ListSchemaFields](/api#operation/ListSchemaFields) call.  Provide this to retrieve the subsequent page.  When paginating, all other parameters provided to [ListSchemaFields](/api#operation/ListSchemaFields) must match the call that provided the page token.
  # @return [ListSchemaFieldsResponse]
  describe 'list_schema_fields test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
