=begin
#Sajari API

#Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.

The version of the OpenAPI document: v4
Contact: support@sajari.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SajariAPIClient::GeneratePipelinesRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SajariAPIClient::GeneratePipelinesRequest do
  let(:instance) { SajariAPIClient::GeneratePipelinesRequest.new }

  describe 'test an instance of GeneratePipelinesRequest' do
    it 'should create an instance of GeneratePipelinesRequest' do
      expect(instance).to be_instance_of(SajariAPIClient::GeneratePipelinesRequest)
    end
  end
  describe 'test attribute "searchable_fields"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "query_training_fields"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
