=begin
#Search.io API

#Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.

The version of the OpenAPI document: v4
Contact: support@search.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SajariAPIClient::GetCollectionRequestView
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SajariAPIClient::GetCollectionRequestView do
  let(:instance) { SajariAPIClient::GetCollectionRequestView.new }

  describe 'test an instance of GetCollectionRequestView' do
    it 'should create an instance of GetCollectionRequestView' do
      expect(instance).to be_instance_of(SajariAPIClient::GetCollectionRequestView)
    end
  end
end
