=begin
#Sajari API

#Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.

The version of the OpenAPI document: v4
Contact: support@sajari.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SajariAPIClient::ProtobufNullValue
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SajariAPIClient::ProtobufNullValue do
  let(:instance) { SajariAPIClient::ProtobufNullValue.new }

  describe 'test an instance of ProtobufNullValue' do
    it 'should create an instance of ProtobufNullValue' do
      expect(instance).to be_instance_of(SajariAPIClient::ProtobufNullValue)
    end
  end
end
