=begin
#Sajari API

#Sajari is a smart, highly-configurable, real-time search service that enables thousands of businesses worldwide to provide amazing search experiences on their websites, stores, and applications.

The version of the OpenAPI document: v4
Contact: support@sajari.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'date'
require 'time'

module SajariAPIClient
  class SchemaFieldMode
    MODE_UNSPECIFIED = "MODE_UNSPECIFIED".freeze
    NULLABLE = "NULLABLE".freeze
    REQUIRED = "REQUIRED".freeze
    UNIQUE = "UNIQUE".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = SchemaFieldMode.constants.select { |c| SchemaFieldMode::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #SchemaFieldMode" if constantValues.empty?
      value
    end
  end
end
