=begin
#Search.io API

#Search.io offers a search and discovery service with Neuralsearch®, the world's first instant AI search technology. Businesses of all sizes use Search.io to build site search and discovery solutions that maximize e-commerce revenue, optimize on-site customer experience, and scale their online presence.

The version of the OpenAPI document: v4
Contact: support@search.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module SajariAPIClient
  class TextPosition
    UNSPECIFIED = "TEXT_POSITION_UNSPECIFIED".freeze
    CENTER = "TEXT_POSITION_CENTER".freeze
    TOP_LEFT = "TEXT_POSITION_TOP_LEFT".freeze
    TOP_RIGHT = "TEXT_POSITION_TOP_RIGHT".freeze
    BOTTOM_LEFT = "TEXT_POSITION_BOTTOM_LEFT".freeze
    BOTTOM_RIGHT = "TEXT_POSITION_BOTTOM_RIGHT".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = TextPosition.constants.select { |c| TextPosition::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #TextPosition" if constantValues.empty?
      value
    end
  end
end
